//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public System.Guid TransactionId { get; set; }
        public string AccNo { get; set; }
        public string TransactionType { get; set; }
        public Nullable<long> DebitCreditBalance { get; set; }
        public Nullable<System.DateTime> DatetimeStamp { get; set; }
        public Nullable<System.Guid> BranchId { get; set; }
        public string EmployeeId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
